kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-pv
  namespace: crudapp-database
spec:
  storageClassName: ""
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # only 1 pod assign at the time
  hostPath:
    path: "/data/db" # path on your worker pod